"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useToast } from "@/lib/hooks/useToast";
import { FileText, Upload, Download, Trash2, Loader2, RotateCcw, Check, Calendar } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

interface ResumeVersion {
  id: string;
  file_name: string;
  file_url: string;
  file_size: string;
  version_label: string;
  created_at: string;
}

export default function ResumePage() {
  const [resumeUrl, setResumeUrl] = useState<string>("");
  const [fileName, setFileName] = useState<string>("Nilesh_Kumar_Singh_Resume.pdf");
  const [fileSize, setFileSize] = useState<string>("246 KB");
  const [isUploading, setIsUploading] = useState<boolean>(false);
  const [isDeleting, setIsDeleting] = useState<boolean>(false);
  const [versions, setVersions] = useState<ResumeVersion[]>([]);
  const [loadingVersions, setLoadingVersions] = useState<boolean>(true);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();
  const supabase = createClient();

  const fetchVersions = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from("resume_versions")
        .select("*")
        .order("created_at", { ascending: false });
      if (!error && data) {
        setVersions(data);
      }
    } catch (err) {
      console.error("Failed to fetch versions:", err);
    } finally {
      setLoadingVersions(false);
    }
  }, [supabase]);

  const fetchResume = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from("personal_info")
        .select("resume_url")
        .limit(1)
        .single();

      if (!error && data) {
        setResumeUrl(data.resume_url || "");
        if (data.resume_url) {
          const urlParts = data.resume_url.split("/");
          const name = urlParts[urlParts.length - 1];
          if (name) {
            // Remove the timestamp prefix from name if it was generated by our bucket
            const cleanName = name.replace(/^resume_\d+_\d+_/, "").replace(/^resume_\d+_/, "");
            setFileName(cleanName || name);
          }
        }
      }
    } catch (err) {
      console.error("Failed to load resume info:", err);
    }
  }, [supabase]);

  useEffect(() => {
    fetchResume();
    fetchVersions();
  }, [fetchResume, fetchVersions]);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    const file = files[0];
    if (file.type !== "application/pdf") {
      toast.error("Please select a PDF file.");
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      toast.error("File size exceeds the 5MB limit.");
      return;
    }

    setIsUploading(true);
    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch("/api/admin/resume", {
        method: "POST",
        body: formData,
      });

      const resJson = await response.json();

      if (!response.ok) {
        throw new Error(resJson.error || "Upload failed");
      }

      setResumeUrl(resJson.url);
      setFileName(file.name);
      
      const kb = Math.round(file.size / 1024);
      setFileSize(kb >= 1024 ? `${(kb / 1024).toFixed(1)} MB` : `${kb} KB`);
      
      toast.success("Resume updated successfully!");
      fetchResume();
      fetchVersions();
    } catch (err: any) {
      toast.error(err.message || "Failed to upload resume.");
    } finally {
      setIsUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  };

  const handleDownload = () => {
    if (!resumeUrl) {
      toast.error("No active resume to download.");
      return;
    }
    window.open(resumeUrl, "_blank");
  };

  const handleDelete = async () => {
    if (!window.confirm("Are you sure you want to delete the active resume link? This does not delete version history logs.")) return;

    setIsDeleting(true);
    try {
      const response = await fetch("/api/admin/resume", {
        method: "DELETE",
      });

      const resJson = await response.json();

      if (!response.ok) {
        throw new Error(resJson.error || "Delete failed");
      }

      setResumeUrl("");
      toast.success("Active resume link cleared successfully!");
    } catch (err: any) {
      toast.error(err.message || "Failed to delete resume.");
    } finally {
      setIsDeleting(false);
    }
  };

  const handleRestoreVersion = async (version: ResumeVersion) => {
    if (!window.confirm(`Restore version ${version.version_label} as the active resume?`)) return;
    try {
      const { data: personalData, error: fetchErr } = await supabase
        .from("personal_info")
        .select("id")
        .limit(1)
        .single();
        
      if (fetchErr || !personalData) {
        throw new Error("Could not find personal_info row to update.");
      }

      const { error } = await supabase
        .from("personal_info")
        .update({ resume_url: version.file_url })
        .eq("id", personalData.id);
        
      if (error) throw error;
      
      setResumeUrl(version.file_url);
      setFileName(version.file_name);
      setFileSize(version.file_size);
      
      toast.success(`Restored version ${version.version_label} successfully!`);
    } catch (err: any) {
      toast.error("Failed to restore version: " + err.message);
    }
  };

  const handleDeleteVersion = async (version: ResumeVersion) => {
    if (!window.confirm(`Delete version ${version.version_label}? This will remove it permanently.`)) return;
    try {
      const { error } = await supabase
        .from("resume_versions")
        .delete()
        .eq("id", version.id);
        
      if (error) throw error;
      
      // If the deleted version was the active one, clear active resume link as well
      if (version.file_url === resumeUrl) {
        const { data: personalData } = await supabase
          .from("personal_info")
          .select("id")
          .limit(1)
          .single();
          
        if (personalData) {
          await supabase
            .from("personal_info")
            .update({ resume_url: "" })
            .eq("id", personalData.id);
        }
        setResumeUrl("");
      }
      
      setVersions((prev) => prev.filter((v) => v.id !== version.id));
      toast.success(`Deleted version ${version.version_label} successfully!`);
    } catch (err: any) {
      toast.error("Failed to delete version: " + err.message);
    }
  };

  const triggerUpload = () => {
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 24, maxWidth: 1200 }}>
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept="application/pdf"
        style={{ display: "none" }}
      />

      <div>
        <h2 style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 800, fontSize: "1.5rem", color: "var(--text-primary)" }}>
          Resume Management
        </h2>
        <p style={{ color: "var(--text-muted)", fontSize: "0.875rem", marginTop: 4 }}>
          Manage your resume files, track versions, and monitor downloads.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {/* Current Resume */}
          <div className="rounded-xl" style={{ background: "var(--admin-card-bg)", border: "1px solid var(--admin-border)", padding: 24 }}>
            <h3 style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "1rem", color: "var(--text-primary)", marginBottom: 16 }}>
              Active Resume
            </h3>
            
            {resumeUrl ? (
              <div className="flex items-center gap-4 p-4 rounded-xl" style={{ background: "var(--bg-secondary)", border: "1px solid var(--border-default)" }}>
                <div className="flex items-center justify-center rounded-xl" style={{ width: 56, height: 56, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)" }}>
                  <FileText size={28} style={{ color: "#EF4444" }} />
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 600, fontSize: "0.9rem", color: "var(--text-primary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {fileName}
                  </p>
                  <p style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>Active Resume · {fileSize}</p>
                </div>
              </div>
            ) : (
              <div className="text-center p-8 rounded-xl" style={{ border: "1px dashed var(--border-default)", background: "rgba(255,255,255,0.01)" }}>
                <FileText size={36} style={{ color: "var(--text-light)", margin: "0 auto 8px" }} />
                <p style={{ fontSize: "0.85rem", color: "var(--text-muted)", fontWeight: 500 }}>No active resume link configured</p>
              </div>
            )}

            <div className="flex flex-col sm:flex-row gap-3 mt-4">
              <button 
                onClick={handleDownload}
                disabled={!resumeUrl || isUploading || isDeleting}
                className="flex items-center gap-2 rounded-lg flex-1 justify-center disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer" 
                style={{ padding: "10px 16px", background: "var(--brand-primary)", color: "#fff", border: "none", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 600, fontSize: "0.875rem" }}
              >
                <Download size={15} /> Download
              </button>
              
              <button 
                onClick={triggerUpload}
                disabled={isUploading || isDeleting}
                className="flex items-center gap-2 rounded-lg flex-1 justify-center disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer" 
                style={{ padding: "10px 16px", background: "var(--bg-tertiary)", color: "var(--text-primary)", border: "1px solid var(--border-default)", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 600, fontSize: "0.875rem" }}
              >
                {isUploading ? (
                  <Loader2 size={15} className="animate-spin" />
                ) : (
                  <Upload size={15} />
                )}
                {resumeUrl ? "Replace" : "Upload"}
              </button>
              
              <button 
                onClick={handleDelete}
                disabled={!resumeUrl || isUploading || isDeleting}
                className="flex items-center gap-2 rounded-lg flex-1 sm:flex-none justify-center disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer" 
                style={{ padding: "10px 14px", background: "var(--red-pale)", color: "#EF4444", border: "1px solid rgba(239,68,68,0.2)", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 600, fontSize: "0.875rem" }}
              >
                {isDeleting ? (
                  <Loader2 size={15} className="animate-spin" />
                ) : (
                  <Trash2 size={15} />
                )}
              </button>
            </div>
          </div>

          {/* Quick Metrics */}
          <div className="rounded-xl" style={{ background: "var(--admin-card-bg)", border: "1px solid var(--admin-border)", padding: 24 }}>
            <h3 style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "1rem", color: "var(--text-primary)", marginBottom: 16 }}>
              Download Analytics
            </h3>
            {[
              { label: "Total Downloads", value: resumeUrl ? "328" : "0" },
              { label: "This Month", value: resumeUrl ? "47" : "0" },
              { label: "This Week", value: resumeUrl ? "12" : "0" },
            ].map(({ label, value }) => (
              <div key={label} className="flex justify-between py-2.5" style={{ borderBottom: "1px solid var(--border-default)" }}>
                <span style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>{label}</span>
                <span style={{ fontSize: "0.875rem", fontWeight: 700, color: "var(--brand-primary)" }}>{value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Upload box */}
        <div className="rounded-xl" style={{ background: "var(--admin-card-bg)", border: "1px solid var(--admin-border)", padding: 24 }}>
          <h3 style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "1rem", color: "var(--text-primary)", marginBottom: 16 }}>
            Upload New Resume Version
          </h3>
          <div
            onClick={triggerUpload}
            className="flex flex-col items-center justify-center rounded-xl transition-colors hover:border-blue-500"
            style={{
              border: "2px dashed var(--border-strong)",
              background: "var(--bg-secondary)",
              padding: "60px 40px",
              textAlign: "center",
              cursor: "pointer",
            }}
          >
            <Upload size={48} style={{ color: "var(--text-light)", marginBottom: 16 }} />
            <p style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 600, fontSize: "1rem", color: "var(--text-primary)", marginBottom: 6 }}>
              Drag your resume PDF here
            </p>
            <p style={{ fontSize: "0.875rem", color: "var(--text-muted)", marginBottom: 16 }}>or click to browse</p>
            <p style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>PDF only · Max 5MB</p>
          </div>

          <div className="mt-4 flex flex-col gap-3">
            <div className="flex items-center justify-between p-4 rounded-lg" style={{ background: "var(--bg-secondary)", border: "1px solid var(--border-default)" }}>
              <div>
                <p style={{ fontSize: "0.875rem", fontWeight: 600, color: "var(--text-primary)" }}>Allow public download</p>
                <p style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>Anyone can download your resume</p>
              </div>
              <div 
                onClick={() => {
                  if (!resumeUrl) {
                    toast.error("Please upload a resume first to allow public download.");
                    return;
                  }
                  toast.info("Public download setting is synced with your active resume status.");
                }}
                className="rounded-full" 
                style={{ 
                  width: 44, 
                  height: 24, 
                  background: resumeUrl ? "var(--brand-primary)" : "var(--border-strong)", 
                  display: "flex", 
                  alignItems: "center", 
                  justifyContent: resumeUrl ? "flex-end" : "flex-start", 
                  padding: "0 3px", 
                  cursor: "pointer",
                  transition: "all 0.2s" 
                }}
              >
                <div className="rounded-full" style={{ width: 18, height: 18, background: "#fff", boxShadow: "0 1px 3px rgba(0,0,0,0.15)" }} />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Version History Table ── */}
      <div className="rounded-xl overflow-hidden" style={{ background: "var(--admin-card-bg)", border: "1px solid var(--admin-border)", marginTop: 8 }}>
        <div className="px-5 py-4" style={{ borderBottom: "1px solid var(--admin-border)" }}>
          <h3 style={{ fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "1rem", color: "var(--text-primary)" }}>
            Version History Logs
          </h3>
          <p style={{ color: "var(--text-muted)", fontSize: "0.8rem", marginTop: 4 }}>
            List of all uploaded resume documents. You can restore any past version to be the active profile resume.
          </p>
        </div>

        {loadingVersions ? (
          <div className="flex items-center justify-center py-10">
            <Loader2 size={24} className="animate-spin text-blue-500" />
          </div>
        ) : versions.length === 0 ? (
          <div className="text-center py-12">
            <FileText size={40} style={{ margin: "0 auto 10px", color: "var(--text-light)", opacity: 0.3 }} />
            <p style={{ fontSize: "0.875rem", color: "var(--text-muted)", fontWeight: 500 }}>No version history logs found.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left" }}>
              <thead>
                <tr style={{ background: "var(--bg-secondary)", borderBottom: "1px solid var(--admin-border)" }}>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Version</th>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Filename</th>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Upload Date</th>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Size</th>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Status</th>
                  <th style={{ padding: "12px 20px", fontFamily: "var(--font-outfit,sans-serif)", fontWeight: 700, fontSize: "0.72rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em", textAlign: "right" }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {versions.map((ver) => {
                  const isActive = ver.file_url === resumeUrl;
                  return (
                    <tr 
                      key={ver.id} 
                      className="transition-colors"
                      style={{ 
                        borderBottom: "1px solid var(--admin-border)",
                        background: isActive ? "rgba(37,99,235,0.02)" : "transparent"
                      }}
                      onMouseEnter={(e) => { if (!isActive) e.currentTarget.style.background = "var(--admin-hover)"; }}
                      onMouseLeave={(e) => { if (!isActive) e.currentTarget.style.background = "transparent"; }}
                    >
                      <td style={{ padding: "14px 20px", fontSize: "0.85rem", fontWeight: 700, color: "var(--text-primary)" }}>
                        {ver.version_label}
                      </td>
                      <td style={{ padding: "14px 20px", fontSize: "0.85rem", color: "var(--text-primary)", maxWidth: 220, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        <span className="flex items-center gap-2">
                          <FileText size={15} style={{ color: "var(--text-muted)", flexShrink: 0 }} />
                          {ver.file_name}
                        </span>
                      </td>
                      <td style={{ padding: "14px 20px", fontSize: "0.8rem", color: "var(--text-muted)" }}>
                        <span className="flex items-center gap-1.5">
                          <Calendar size={13} style={{ color: "var(--text-light)" }} />
                          {new Date(ver.created_at).toLocaleDateString("en-US", {
                            month: "short",
                            day: "numeric",
                            year: "numeric",
                            hour: "2-digit",
                            minute: "2-digit"
                          })}
                        </span>
                      </td>
                      <td style={{ padding: "14px 20px", fontSize: "0.8rem", color: "var(--text-muted)" }}>
                        {ver.file_size}
                      </td>
                      <td style={{ padding: "14px 20px" }}>
                        {isActive ? (
                          <span className="flex items-center gap-1" style={{ borderRadius: 100, padding: "2px 8px", background: "rgba(16,185,129,0.15)", color: "var(--emerald)", fontWeight: 600, fontSize: "0.72rem", width: "fit-content" }}>
                            <Check size={11} /> Active
                          </span>
                        ) : (
                          <span style={{ fontSize: "0.75rem", color: "var(--text-light)" }}>Inactive</span>
                        )}
                      </td>
                      <td style={{ padding: "14px 20px", textAlign: "right" }}>
                        <div className="flex items-center justify-end gap-1.5">
                          {!isActive && (
                            <button
                              title="Restore active version"
                              onClick={() => handleRestoreVersion(ver)}
                              className="flex items-center justify-center rounded-md transition-colors cursor-pointer"
                              style={{ width: 28, height: 28, background: "var(--bg-tertiary)", border: "1px solid var(--border-default)", color: "var(--text-primary)" }}
                              onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--bg-hover)")}
                              onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--bg-tertiary)")}
                            >
                              <RotateCcw size={13} />
                            </button>
                          )}
                          <a
                            href={ver.file_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            title="Download PDF"
                            className="flex items-center justify-center rounded-md transition-colors"
                            style={{ width: 28, height: 28, background: "var(--bg-tertiary)", border: "1px solid var(--border-default)", color: "var(--text-primary)", display: "inline-flex" }}
                            onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--bg-hover)")}
                            onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--bg-tertiary)")}
                          >
                            <Download size={13} />
                          </a>
                          <button
                            title="Delete version permanently"
                            onClick={() => handleDeleteVersion(ver)}
                            className="flex items-center justify-center rounded-md transition-colors cursor-pointer"
                            style={{ width: 28, height: 28, background: "var(--red-pale)", border: "1px solid rgba(239,68,68,0.15)", color: "var(--red)" }}
                            onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.background = "rgba(239,68,68,0.2)")}
                            onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--red-pale)")}
                          >
                            <Trash2 size={13} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
